include src/str/any_str/Makefile
include src/str/borrowing/Makefile
include src/str/c_str/Makefile
include src/str/checking/Makefile
include src/str/comparison/Makefile

STR_SRCS = \
	${addprefix any_str/,$(ANY_STR_SRCS)} \
	${addprefix borrowing/,$(STR_BORROWING_SRCS)} \
	${addprefix c_str/,$(STR_C_STR_SRCS)} \
	${addprefix checking/,$(STR_CHECKING_SRCS)} \
	${addprefix comparison/,$(STR_COMPARISON_SRCS)}
