include src/str/any_str/Makefile
include src/str/borrowed_str/Makefile
include src/str/c_str/Makefile

STR_SRCS = \
	${addprefix any_str/,$(ANY_STR_SRCS)} \
	${addprefix borrowed_str/,$(BORROWED_STR_SRCS)} \
	${addprefix c_str/,$(C_STR_SRCS)}
