include src/str/adding/Makefile
include src/str/borrowing/Makefile
include src/str/c_str/Makefile
include src/str/casing/Makefile
include src/str/checking/Makefile
include src/str/comparison/Makefile
include src/str/cropping/Makefile
include src/str/search/Makefile
include src/str/splitting/Makefile
include src/str/positionning/Makefile
include src/str/stripping/Makefile
include src/str/printing/Makefile

STR_SRCS = \
	allocation.c \
	capacity.c \
	${addprefix adding/,$(STR_ADDING_SRCS)} \
	${addprefix borrowing/,$(STR_BORROWING_SRCS)} \
	${addprefix casing/,$(STR_CASING_SRCS)} \
	${addprefix c_str/,$(STR_C_STR_SRCS)} \
	${addprefix checking/,$(STR_CHECKING_SRCS)} \
	${addprefix comparison/,$(STR_COMPARISON_SRCS)} \
	${addprefix cropping/,$(STR_CROPPING_SRCS)} \
	${addprefix search/,$(STR_SEARCH_SRCS)} \
	${addprefix splitting/,$(STR_SPLITTING_SRCS)} \
	${addprefix positionning/,$(STR_POSITIONNING_SRCS)} \
	${addprefix stripping/,$(STR_STRIPPING_SRCS)} \
	${addprefix printing/,$(STR_PRINTING_SRCS)} \
