SRCS_CHAR = \
	ft_char_isalnum.c \
	ft_char_isalpha.c \
	ft_char_isascii.c \
	ft_char_isdigit.c \
	ft_char_islower.c \
	ft_char_isprint.c \
	ft_char_isupper.c \
	ft_char_tolower.c \
	ft_char_toupper.c
