CHAR_SRCS = \
	ft_char_is_alnum.c \
	ft_char_is_alpha.c \
	ft_char_is_ascii.c \
	ft_char_is_digit.c \
	ft_char_is_lower.c \
	ft_char_is_print.c \
	ft_char_is_blank.c \
	ft_char_is_upper.c \
	ft_char_swap_case.c \
	ft_char_to_lower.c \
	ft_char_to_upper.c \
