include src/printing/ostream/Makefile
include src/printing/fixed_types/Makefile

PRINTING_SRCS = \
	${addprefix ostream/,$(PRINTING_OSTREAM_SRCS)} \
	${addprefix fixed_types/,$(PRINTING_FIXED_TYPES_SRCS)} \
	ft_safe_read.c \
	ft_safe_write.c