PRINTF_SRCS = \
	ft_stdout.c\
	ft_stderr.c\
	ft_printf.c \
	ft_format_label.c \
	ft_str_scanner1.c \
	ft_str_scanner2.c \
	label_printers/ft_c_str_label_printer.c \
	label_printers/ft_str_label_printer.c \
	label_printers/ft_char_label_printer.c
