include src/text/any_str/Makefile
include src/text/borrowed_str/Makefile
include src/text/c_str/Makefile

TEXT_SRCS = \
	${addprefix any_str/,$(ANY_STR_SRCS)} \
	${addprefix borrowed_str/,$(BORROWED_STR_SRCS)} \
	${addprefix c_str/,$(C_STR_SRCS)}
