include src/text/any_str/Makefile
include src/text/borrowed_str/Makefile
include src/text/char/Makefile

TEXT_SRCS = \
	${addprefix any_str/,$(ANY_STR_SRCS)} \
	${addprefix borrowed_str/,$(BORROWED_SRCS)} \
	${addprefix char/,$(CHAR_SRCS)}
