IO_PRINTF_SRCS = \
	label_printers/c_str_label_printer.c \
	label_printers/str_label_printer.c \
	label_printers/char_label_printer.c \
	format_label.c \
	printf.c \
	stderr.c \
	stdout.c \
	str_scanner1.c \
	str_scanner2.c \
