include first_part/char/Makefile
include first_part/mem/Makefile
include first_part/str/Makefile

SRCS_FIRST_PART = \
	$(addprefix char/,${SRCS_CHAR}) \
	$(addprefix mem/, ${SRCS_MEM}) \
	$(addprefix str/, ${SRCS_STR})
