STR_SRCS = \
	ft_str_dup_c_str.c \
	ft_str_from_int.c \
	ft_str_reserve_exact.c \
	ft_str_reserve_pow2.c \
	ft_str_free.c \
	ft_str_dup.c \
	ft_str_dup_slice.c \
	ft_str_set_slice.c \
	ft_str_append.c \
	ft_str_prepend.c \
	ft_str_split_alloc.c \
