PRINTING_FIXED_TYPES_SRCS = \
	unsigned/ft_u8_print.c \
	unsigned/ft_u16_print.c \
	unsigned/ft_u32_print.c \
	unsigned/ft_u64_print.c \
	signed/ft_i8_print.c \
	signed/ft_i16_print.c \
	signed/ft_i32_print.c \
	signed/ft_i64_print.c \
	floating/ft_f32_print.c \
	# floating/ft_f64_print.c \
	floating/ft_f128_print.c \
	complex/ft_cf32_print.c \
	complex/ft_cf64_print.c \
	complex/ft_cf128_print.c \
