IO_PRINTING_SRCS = \
	complex/cf32_print.c \
	complex/cf64_print.c \
	complex/cf80_print.c \
	complex/cf128_print.c \
	floating/f32_print.c \
	floating/f64_print.c \
	floating/f80_print.c \
	floating/f128_print.c \
	signed/i8_print.c \
	signed/i16_print.c \
	signed/i32_print.c \
	signed/i64_print.c \
	unsigned/u8_print.c \
	unsigned/u16_print.c \
	unsigned/u32_print.c \
	unsigned/u64_print.c \
	safe_write.c \
