include src/io/printing/printing_fixed_types/Makefile

IO_PRINTING_SRCS = \
	${addprefix printing_fixed_types/,$(IO_PRINTING_FIXED_TYPES_SRCS)} \
	label_printers/c_str_label_printer.c \
	label_printers/str_label_printer.c \
	label_printers/char_label_printer.c \
	ostream/array_ostream.c \
	ostream/buffered_ostream.c \
	ostream/fd_ostream.c \
	ostream/fixed_str_ostream.c \
	ostream/ostream_base.c \
	ostream/ostream.c \
	format_label.c \
	printf.c \
	safe_write.c \
	stderr.c\
	stdout.c\
	str_scanner1.c \
	str_scanner2.c \
