include src/io/ostream/Makefile
include src/io/parsing/Makefile
include src/io/printf/Makefile
include src/io/printing/Makefile

IO_SRCS = \
	${addprefix ostream/,$(IO_OSTREAM_SRCS)} \
	${addprefix parsing/,$(IO_PARSING_SRCS)} \
	${addprefix printf/,$(IO_PRINTF_SRCS)} \
	${addprefix printing/,$(IO_PRINTING_SRCS)} \
