ANY_STR_SRCS = \
	ft_str_borrow_c_str.c \
	ft_str_get_char.c \
	ft_str_borrow_slice.c \
	ft_str_at_char.c \
	ft_str_first_char.c \
	ft_str_last_char.c \
	ft_str_compare.c \
	ft_str_startswith.c \
	ft_str_equal.c \
	ft_str_find_char.c \
	ft_str_find_str.c \
	ft_str_split_borrow.c \
	ft_str_slice_array_free.c
