include src/bounds/min/Makefile
include src/bounds/max/Makefile
include src/bounds/clamp/Makefile
include src/bounds/abs/Makefile

BOUNDS_SRCS = \
	${addprefix min/,$(BOUNDS_MIN_SRCS)} \
	${addprefix max/,$(BOUNDS_MAX_SRCS)} \
	${addprefix clamp/,$(BOUNDS_CLAMP_SRCS)} \
	${addprefix abs/,$(BOUNDS_ABS_SRCS)} \
