include src/bounds/min/Makefile
include src/bounds/max/Makefile
include src/bounds/clamp/Makefile

BOUNDS_SRCS = \
	${addprefix min/,$(BOUNDS_MIN_SRCS)} \
	${addprefix max/,$(BOUNDS_MAX_SRCS)} \
	${addprefix clamp/,$(BOUNDS_CLAMP_SRCS)} \
