include src/data/array/Makefile
include src/data/char/Makefile
include src/data/iterator/Makefile
include src/data/mem/Makefile
include src/data/str/Makefile

DATA_SRCS = \
	${addprefix array/,$(DATA_ARRAY_SRCS)} \
	${addprefix char/,$(DATA_CHAR_SRCS)} \
	${addprefix iterator/,$(DATA_ITERATOR_SRCS)} \
	${addprefix mem/,$(DATA_MEM_SRCS)} \
	${addprefix str/,$(DATA_STR_SRCS)} \
