include src/data/char/Makefile
include src/data/iterator/Makefile
include src/data/mem/Makefile
include src/data/str/Makefile

DATA_SRCS = \
	${addprefix CHAR/,$(DATA_CHAR_SRCS)} \
	${addprefix ITERATOR/,$(DATA_ITERATOR_SRCS)} \
	${addprefix MEM/,$(DATA_MEM_SRCS)} \
	${addprefix STR/,$(DATA_STR_SRCS)} \
